import { CheckCircle2,ExternalLink,Mail,MessageCircle,Settings2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { isMailjetConfigured } from "@/lib/mailjet/client";
import { isWhatsAppCloudConfigured } from "@/lib/whatsapp/client";
import { MailjetTestButton,WhatsAppTestButton } from "./test-buttons";

export default function IntegrationsPage(){const mailjet=isMailjetConfigured();const whatsapp=isWhatsAppCloudConfigured();return <div className="mx-auto max-w-5xl space-y-8"><div><span className="inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1.5 text-sm font-semibold text-primary"><Settings2 className="size-4"/>Phase 4 integrations</span><h1 className="mt-4 text-3xl font-bold">Automated messaging</h1><p className="mt-2 text-muted-foreground">Test Mailjet delivery and connect Meta WhatsApp Cloud API for approved template messages.</p></div><div className="grid gap-6 md:grid-cols-2"><Card className="border-0"><CardHeader><CardTitle className="flex items-center gap-2"><Mail className="size-5 text-primary"/>Mailjet <Badge variant={mailjet?"success":"warning"}>{mailjet?"Configured":"Setup required"}</Badge></CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Sends registration receipts, reminders, attendance confirmations, and named certificate attachments.</p>{mailjet&&<MailjetTestButton/>}</CardContent></Card><Card className="border-0"><CardHeader><CardTitle className="flex items-center gap-2"><MessageCircle className="size-5 text-primary"/>WhatsApp <Badge variant={whatsapp?"success":"warning"}>{whatsapp?"Cloud API ready":"Meta setup required"}</Badge></CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Automated sending requires a Meta Business account, a WhatsApp-enabled phone number, approved templates, access token, and recipient consent.</p><Button asChild variant="outline"><a href="https://developers.facebook.com/apps/" rel="noreferrer" target="_blank">Open Meta Developer setup <ExternalLink className="size-4"/></a></Button>{whatsapp&&<WhatsAppTestButton/>}{!whatsapp&&<div className="rounded-lg bg-muted p-3 text-sm"><p className="font-semibold">Required server variables</p><p className="mt-1 text-muted-foreground">WHATSAPP_PROVIDER=meta_cloud, WHATSAPP_ACCESS_TOKEN, WHATSAPP_PHONE_NUMBER_ID, and approved template names.</p></div>}</CardContent></Card></div><Card className="border-0 bg-emerald-50"><CardContent className="flex gap-3 p-5 text-emerald-900"><CheckCircle2 className="mt-0.5 size-5 shrink-0"/><p className="text-sm">Until Meta setup is complete, participant acknowledgements remain available as pre-filled WhatsApp links; automated email and the rest of the follow-up pipeline continue independently.</p></CardContent></Card></div>}
